theme: jekyll-theme-minimal
title: Yerkezhan Abdullayeva
logo: /figures/Yerkezhan_photo.png
description: Natural Language Processing (NLP) enthusiast
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
