theme: jekyll-theme-minimal
title: Yerkezhan Abdullayeva
logo: /figures/Yerkezhan_photo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
